import sqlite3
conn = sqlite3.connect("data/sequoia_v2.db")
c = conn.execute("SELECT MAX(date), COUNT(DISTINCT symbol) FROM stock_daily")
r = c.fetchone()
print("===DB_STATUS===")
print("max_date:", r[0])
print("stock_count:", r[1])
c2 = conn.execute("SELECT MAX(date), MAX(end_time) FROM sync_log")
r2 = c2.fetchone()
print("sync_max_date:", r2[0])
print("sync_last_time:", r2[1])
c3 = conn.execute("SELECT MAX(date) FROM index_daily")
r3 = c3.fetchone()
print("index_max_date:", r3[0])
c4 = conn.execute("SELECT COUNT(*) FROM stock_daily WHERE date='2026-06-10'")
r4 = c4.fetchone()
print("today_records_0610:", r4[0])
c5 = conn.execute("SELECT COUNT(*) FROM stock_daily WHERE date='2026-06-09'")
r5 = c5.fetchone()
print("yest_records_0609:", r5[0])
conn.close()
